licenses(["notice"])

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "hand",
    deps = [
        "//mediapipe/examples/desktop:run_hand",
        "//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",
    ],
)
